# Generated by Django 4.1.2 on 2022-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fiat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
