# Generated by Django 4.1.2 on 2022-10-28 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0002_person_fiat_person_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_buy_order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.person'),
        ),
    ]
