# Generated by Django 4.1.2 on 2022-10-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0003_alter_pending_buy_order_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.person')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_seller', to='myUser.person')),
            ],
        ),
    ]
