# Generated by Django 4.1.2 on 2022-10-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_buy_order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_buy_order', to='myUser.person'),
        ),
    ]
