# Generated by Django 4.1.2 on 2022-10-29 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0007_alter_pending_buy_order_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_buy_order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.person'),
        ),
        migrations.AlterField(
            model_name='pending_sell_order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUser.person'),
        ),
    ]
