# Generated by Django 4.1.2 on 2022-10-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0009_alter_pending_buy_order_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_buy_order',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pending_sell_order',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.CharField(max_length=32),
        ),
    ]
